---
description: 'Install quickstart toolchain'
inputs:
  platform-tools-version:
    default: 'v1.51'
    description: 'Solana platform-tools version'
    required: false
  sbpf-revision:
    default: 'fae3e8a'
    description: 'sbpf CLI rev (git commit hash, tag, or branch) to install'
    required: false
  solana-version:
    default: 'v3.1.2'
    description: 'Solana version to install'
    required: false
name: 'Install toolchain'
outputs:
  platform:
    description: 'Platform identifier (OS-ARCH)'
    value: '${{ steps.set-platform.outputs.platform }}'
runs:
  steps:
  - id: 'set-platform'
    name: 'Set platform identifier'
    run: |
      PLATFORM="${{ runner.os }}-${{ runner.arch }}"
      echo "PLATFORM=${PLATFORM}" >> $GITHUB_ENV
      echo "platform=${PLATFORM}" >> $GITHUB_OUTPUT
    shell: 'sh'
  - name: 'Add Solana tools to PATH'
    run: '${{ github.action_path }}/scripts/add-solana-tools-to-path.sh'
    shell: 'sh'
  - id: 'cache-toolchain'
    name: 'Cache toolchain components'
    uses: 'actions/cache@v4'
    with:
      key: 'solana-opcode-guide-toolchain-${{
            inputs.solana-version }}-${{
            inputs.platform-tools-version }}-${{
            inputs.sbpf-revision }}-${{
            env.PLATFORM }}'
      path: |
        ~/.cache/solana
        ~/.cargo/bin/sbpf
        ~/.local/share/solana
  - if: 'steps.cache-toolchain.outputs.cache-hit != ''true'''
    name: 'Install Solana toolchain'
    run: >-
      ${{ github.action_path }}/scripts/install-solana.sh
      "${{ inputs.solana-version }}"
    shell: 'sh'
  - if: 'steps.cache-toolchain.outputs.cache-hit != ''true'''
    name: 'Install platform-tools'
    run: >-
      cargo-build-sbf --install-only --tools-version
      ${{ inputs.platform-tools-version }}
    shell: 'sh'
  # The platform tools install command skips over the SBF install script (in
  # the same directory as dump.sh), even though `cargo-build-sbf` runs it at
  # build time. This step caches the result.
  - if: 'steps.cache-toolchain.outputs.cache-hit != ''true'''
    name: 'Run platform tools SBF install script'
    run: 'install.sh'
    shell: 'sh'
  - if: 'steps.cache-toolchain.outputs.cache-hit != ''true'''
    name: 'Install sbpf CLI'
    run: >-
      cargo install --git https://github.com/blueshift-gg/sbpf.git
      --rev ${{ inputs.sbpf-revision }}
    shell: 'sh'
  - name: 'Verify all tools are installed'
    run: '${{ github.action_path }}/scripts/verify-tools.sh'
    shell: 'sh'
  using: 'composite'
...
