---
description: 'Install quickstart toolchain'
inputs:
  platform-tools-version:
    default: 'v1.51'
    description: 'Solana platform-tools version'
    required: false
  sbpf-revision:
    default: 'fae3e8a'
    description: 'sbpf CLI rev (git commit hash, tag, or branch) to install'
    required: false
  solana-version:
    default: 'v3.1.2'
    description: 'Solana version to install'
    required: false
name: 'Install toolchain'
outputs:
  platform:
    description: 'Platform identifier (OS-ARCH)'
    value: '${{ steps.set-path-vars.outputs.platform }}'
runs:
  steps:
  - env:
      RUNNER_ARCH: '${{ runner.arch }}'
      RUNNER_OS: '${{ runner.os }}'
    id: 'set-path-vars'
    name: 'Set path variables'
    run: '${{ github.action_path }}/scripts/set-path-vars.sh'
    shell: 'sh'
  - id: 'cache-toolchain'
    name: 'Cache toolchain components'
    uses: 'actions/cache@v4'
    with:
      key: 'solana-opcode-guide-toolchain-${{
            inputs.solana-version }}-${{
            inputs.platform-tools-version }}-${{
            inputs.sbpf-revision }}-${{
            env.PLATFORM }}'
      path: |
        ~/.cache/solana
        ~/.cargo/bin/sbpf
        ~/.local/share/solana
  - if: 'steps.cache-toolchain.outputs.cache-hit != ''true'''
    name: 'Install tools'
    run: >-
      ${{ github.action_path }}/scripts/install-tools.sh
      "${{ inputs.solana-version }}"
      "${{ inputs.platform-tools-version }}"
      "${{ inputs.sbpf-revision }}"
    shell: 'sh'
  - name: 'Verify tools'
    run: '${{ github.action_path }}/scripts/verify-tools.sh'
    shell: 'sh'
  using: 'composite'
...
