# cspell:word objdump
# cspell:word readelf
# cspell:word rustup
---
description: 'Install quickstart toolchain (rustup, Solana, sbpf)'
inputs:
  platform-tools-version-sbpf-v3-arch:
    default: 'v1.52'
    description: 'Solana platform-tools version for SBPF v3 architecture'
    required: false
  platform-tools-version-sbpf-v4-arch:
    default: 'v1.51'
    description: 'Solana platform-tools version for SBPF v4 architecture'
    required: false
  sbpf-revision:
    default: '97f6ead8fe68f6329fb5015d7edbc6dcc2390d8b'
    description: 'SBPF revision (git commit hash, tag, or branch) to install'
    required: false
  solana-version:
    default: 'v3.1.2'
    description: 'Solana version to install'
    required: false
name: 'Install toolchain'
outputs:
  platform:
    description: 'Platform identifier (OS-ARCH)'
    value: '${{ steps.set-platform.outputs.platform }}'
runs:
  steps:
  - id: 'set-platform'
    name: 'Set platform identifier'
    run: |
      PLATFORM="${{ runner.os }}-${{ runner.arch }}"
      echo "PLATFORM=${PLATFORM}" >> $GITHUB_ENV
      echo "platform=${PLATFORM}" >> $GITHUB_OUTPUT
    shell: 'sh'
  - id: 'cache-rustup'
    name: 'Cache rustup'
    uses: 'actions/cache@v4'
    with:
      key: 'rustup-only-${{ env.PLATFORM }}'
      path: |
        ~/.cargo/bin/rustup
        ~/.cargo/bin/rustup-init
        ~/.rustup/settings.toml
        ~/.rustup/toolchains
  - if: 'steps.cache-rustup.outputs.cache-hit != ''true'''
    name: 'Install rustup (no default toolchain)'
    run: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain none
      echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    shell: 'sh'
  - if: 'steps.cache-rustup.outputs.cache-hit == ''true'''
    name: 'Add rustup to PATH'
    run: 'echo "$HOME/.cargo/bin" >> $GITHUB_PATH'
    shell: 'sh'
  - name: 'Verify rustup is installed'
    run: 'rustup --version'
    shell: 'sh'
  - id: 'cache-solana'
    name: 'Cache Solana toolchain'
    uses: 'actions/cache@v4'
    with:
      key: 'solana-${{ inputs.solana-version }}-${{ env.PLATFORM }}'
      path: '~/.local/share/solana'
  - if: 'steps.cache-solana.outputs.cache-hit != ''true'''
    name: 'Install Solana toolchain'
    run: >-
      ${{ github.action_path }}/scripts/install-solana.sh
      "${{ inputs.solana-version }}"
    shell: 'sh'
  - name: 'Add Solana tools to PATH'
    run: |
      SOLANA_RELEASE="$HOME/.local/share/solana/install/active_release/bin"
      SBPF_TOOLS="$SOLANA_RELEASE/platform-tools-sdk/sbf"
      echo "$SOLANA_RELEASE" >> $GITHUB_PATH
      echo "$SBPF_TOOLS/scripts" >> $GITHUB_PATH
      echo "$SBPF_TOOLS/dependencies/platform-tools/llvm/bin" >> $GITHUB_PATH
    shell: 'sh'
  - id: 'cache-platform-tools-sbpf-v3'
    name: 'Cache platform-tools (SBPF v3)'
    uses: 'actions/cache@v4'
    with:
      key: 'platform-tools-${{ inputs.platform-tools-version-sbpf-v3-arch
            }}-${{ env.PLATFORM }}'
      path: '~/.cache/solana/${{ inputs.platform-tools-version-sbpf-v3-arch }}'
  - if: 'steps.cache-platform-tools-sbpf-v3.outputs.cache-hit != ''true'''
    name: 'Install platform-tools (SBPF v3)'
    run: >-
      cargo-build-sbf
      --tools-version ${{ inputs.platform-tools-version-sbpf-v3-arch }}
      --install-only
    shell: 'sh'
  - id: 'cache-platform-tools-sbpf-v4'
    name: 'Cache platform-tools (SBPF v4)'
    uses: 'actions/cache@v4'
    with:
      key: 'platform-tools-${{ inputs.platform-tools-version-sbpf-v4-arch
            }}-${{ env.PLATFORM }}'
      path: '~/.cache/solana/${{ inputs.platform-tools-version-sbpf-v4-arch }}'
  - if: 'steps.cache-platform-tools-sbpf-v4.outputs.cache-hit != ''true'''
    name: 'Install platform-tools (SBPF v4)'
    run: >-
      cargo-build-sbf
      --tools-version ${{ inputs.platform-tools-version-sbpf-v4-arch }}
      --install-only
    shell: 'sh'
  - name: 'Add platform-tools Rust to PATH'
    run: |
      PLATFORM_TOOLS_RUST="$HOME/.local/share/solana/install/active_release/bin/platform-tools-sdk/sbf/dependencies/platform-tools/rust/bin"
      echo "$PLATFORM_TOOLS_RUST" >> $GITHUB_PATH
    shell: 'sh'
  - name: 'Verify rustc is installed'
    run: 'rustc --version'
    shell: 'sh'
  - name: 'Verify cargo is installed'
    run: 'cargo --version'
    shell: 'sh'
  - id: 'cache-sbpf'
    name: 'Cache sbpf'
    uses: 'actions/cache@v4'
    with:
      key: 'sbpf-${{ inputs.sbpf-revision }}-${{ env.PLATFORM }}'
      path: '~/.cargo/bin/sbpf'
  - if: 'steps.cache-sbpf.outputs.cache-hit != ''true'''
    name: 'Install sbpf CLI'
    run: >-
      cargo install --git https://github.com/blueshift-gg/sbpf.git
      --rev ${{ inputs.sbpf-revision }}
    shell: 'sh'
  - name: 'Verify llvm-objdump is installed'
    run: 'llvm-objdump --version'
    shell: 'sh'
  - name: 'Verify llvm-readelf is installed'
    run: 'llvm-readelf --version'
    shell: 'sh'
  - name: 'Verify solana is installed'
    run: 'solana --version'
    shell: 'sh'
  - name: 'Verify sbpf is installed'
    run: 'sbpf --version'
    shell: 'sh'
  - name: 'Verify dump.sh is installed'
    run: 'which dump.sh'
    shell: 'sh'
  using: 'composite'
...
