---
description: 'Install quickstart toolchain'
inputs:
  platform-tools-version-sbpf-v3-arch:
    default: 'v1.52'
    description: 'Solana platform-tools version for SBPF v3 architecture'
    required: false
  platform-tools-version-sbpf-v4-arch:
    default: 'v1.51'
    description: 'Solana platform-tools version for SBPF v4 architecture'
    required: false
  sbpf-revision:
    default: '97f6ead8fe68f6329fb5015d7edbc6dcc2390d8b'
    description: 'sbpf CLI rev (git commit hash, tag, or branch) to install'
    required: false
  solana-version:
    default: 'v3.1.2'
    description: 'Solana version to install'
    required: false
name: 'Install toolchain'
outputs:
  platform:
    description: 'Platform identifier (OS-ARCH)'
    value: '${{ steps.set-platform.outputs.platform }}'
runs:
  steps:
  - id: 'set-platform'
    name: 'Set platform identifier'
    run: |
      PLATFORM="${{ runner.os }}-${{ runner.arch }}"
      echo "PLATFORM=${PLATFORM}" >> $GITHUB_ENV
      echo "platform=${PLATFORM}" >> $GITHUB_OUTPUT
    shell: 'sh'
  - name: 'Add Solana tools to PATH'
    run: '${{ github.action_path }}/scripts/add-solana-tools-to-path.sh'
    shell: 'sh'
  - id: 'cache-toolchain'
    name: 'Cache all toolchain components'
    uses: 'actions/cache@v4'
    with:
      key: 'solana-opcode-guide-toolchain-${{
            inputs.solana-version }}-${{
            inputs.platform-tools-version-sbpf-v3-arch }}-${{
            inputs.platform-tools-version-sbpf-v4-arch }}-${{
            inputs.sbpf-revision }}-${{
            env.PLATFORM }}'
      path: |
        ~/.local/share/solana
        ~/.cache/solana/${{ inputs.platform-tools-version-sbpf-v3-arch }}
        ~/.cache/solana/${{ inputs.platform-tools-version-sbpf-v4-arch }}
        ~/.cargo/bin/sbpf
  - if: 'steps.cache-toolchain.outputs.cache-hit != ''true'''
    name: 'Install Solana toolchain'
    run: >-
      ${{ github.action_path }}/scripts/install-solana.sh
      "${{ inputs.solana-version }}"
    shell: 'sh'
  - if: 'steps.cache-toolchain.outputs.cache-hit != ''true'''
    name: 'Install platform-tools (SBPF v3)'
    run: >-
      ${{ github.action_path }}/scripts/install-platform-tools.sh
      ${{ inputs.platform-tools-version-sbpf-v3-arch }}
    shell: 'sh'
  - if: 'steps.cache-toolchain.outputs.cache-hit != ''true'''
    name: 'Install platform-tools (SBPF v4)'
    run: >-
      ${{ github.action_path }}/scripts/install-platform-tools.sh
      ${{ inputs.platform-tools-version-sbpf-v4-arch }}
    shell: 'sh'
  - if: 'steps.cache-toolchain.outputs.cache-hit != ''true'''
    name: 'Install sbpf CLI'
    run: >-
      cargo install --git https://github.com/blueshift-gg/sbpf.git
      --rev ${{ inputs.sbpf-revision }}
    shell: 'sh'
  - name: 'Verify all tools are installed'
    run: '${{ github.action_path }}/scripts/verify-tools.sh'
    shell: 'sh'
  using: 'composite'
...
