# cspell:word awalsh
# cspell:word dtolnay
# cspell:word objdump
# cspell:word readelf
# cspell:word rustup
---
description: 'Install quickstart toolchain (Rust, Solana, sbpf)'
inputs:
  platform-tools-version:
    default: 'v1.51'
    description: 'Solana platform-tools version to install'
    required: false
  rust-toolchain-version:
    default: '1.91.0'
    description: 'Rust toolchain version to install'
    required: false
  sbpf-revision:
    default: '97f6ead8fe68f6329fb5015d7edbc6dcc2390d8b'
    description: 'SBPF revision (git commit hash, tag, or branch) to install'
    required: false
  solana-version:
    default: 'v3.1.2'
    description: 'Solana version to install'
    required: false
name: 'Install toolchain'
runs:
  steps:
  - name: 'Set platform identifier'
    run: 'echo "PLATFORM=${{ runner.os }}-${{ runner.arch }}" >> $GITHUB_ENV'
    shell: 'sh'
  - id: 'cache-rust'
    name: 'Cache Rust toolchain'
    uses: 'actions/cache@v4'
    with:
      key: 'rust-${{ inputs.rust-toolchain-version }}-${{ env.PLATFORM }}'
      path: |
        ~/.cargo/registry
        ~/.cargo/git
        ~/.rustup
  - if: 'steps.cache-rust.outputs.cache-hit != ''true'''
    name: 'Install Rust toolchain'
    uses: 'dtolnay/rust-toolchain@master'
    with:
      toolchain: '${{ inputs.rust-toolchain-version }}'
  - if: 'steps.cache-rust.outputs.cache-hit == ''true'''
    name: 'Add Rust to PATH'
    run: 'echo "$HOME/.cargo/bin" >> $GITHUB_PATH'
    shell: 'sh'
  - id: 'cache-solana'
    name: 'Cache Solana toolchain'
    uses: 'actions/cache@v4'
    with:
      key: 'solana-${{ inputs.solana-version }}-${{ env.PLATFORM }}'
      path: '~/.local/share/solana'
  - if: 'steps.cache-solana.outputs.cache-hit != ''true'''
    name: 'Install Solana toolchain'
    run: >-
      ${{ github.action_path }}/scripts/install-solana.sh
      "${{ inputs.solana-version }}"
    shell: 'sh'
  - name: 'Add Solana tools to PATH'
    run: |
      SOLANA_RELEASE="$HOME/.local/share/solana/install/active_release/bin"
      SBPF_TOOLS="$SOLANA_RELEASE/platform-tools-sdk/sbf"
      echo "$SOLANA_RELEASE" >> $GITHUB_PATH
      echo "$SBPF_TOOLS/scripts" >> $GITHUB_PATH
      echo "$SBPF_TOOLS/dependencies/platform-tools/llvm/bin" >> $GITHUB_PATH
    shell: 'sh'
  - id: 'cache-platform-tools'
    name: 'Cache Solana platform tools'
    uses: 'actions/cache@v4'
    with:
      key: >-
        platform-tools-${{ inputs.platform-tools-version }}-${{ env.PLATFORM }}
      path: '~/.cache/solana'
  - name: 'Install Solana platform tools'
    run: >-
      cargo-build-sbf
      --tools-version ${{ inputs.platform-tools-version }}
      --install-only
    shell: 'sh'
  - id: 'cache-sbpf'
    name: 'Cache sbpf'
    uses: 'actions/cache@v4'
    with:
      key: 'sbpf-${{ inputs.sbpf-revision }}-${{ env.PLATFORM }}'
      path: '~/.cargo/bin/sbpf'
  - if: 'steps.cache-sbpf.outputs.cache-hit != ''true'''
    name: 'Install sbpf CLI'
    run: >-
      cargo install --git https://github.com/blueshift-gg/sbpf.git
      --rev ${{ inputs.sbpf-revision }}
    shell: 'sh'
  - name: 'Verify llvm-objdump is installed'
    run: 'llvm-objdump --version'
    shell: 'sh'
  - name: 'Verify llvm-readelf is installed'
    run: 'llvm-readelf --version'
    shell: 'sh'
  - name: 'Verify solana is installed'
    run: 'solana --version'
    shell: 'sh'
  - name: 'Verify sbpf is installed'
    run: 'sbpf --version'
    shell: 'sh'
  - name: 'Verify dump.sh is installed'
    run: 'which dump.sh'
    shell: 'sh'
  using: 'composite'
...
